<a href="https://colab.research.google.com/github/satheesh3180/load_breast_cancer-/blob/main/RNN_LSTM%26GRU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

# --------------------------------------------
# 🧩 1️⃣ Embedding Layers & Sequence Preprocessing
# --------------------------------------------
texts = [
    "I love this movie",
    "This movie was terrible",
    "Fantastic acting and story",
    "I hated this film",
    "Amazing direction and music",
    "The movie was boring"
]

# Labels for sentiment (1 = positive, 0 = negative)
labels = np.array([1, 0, 1, 0, 1, 0])

# Convert text → numbers
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
sequences = tokenizer.texts_to_sequences(texts)
padded = pad_sequences(sequences, padding='post')

print("📘 Word Index (meaning of each word):")
print(tokenizer.word_index)
print("\n🔢 Padded Sequences (converted text):")
print(padded)

# --------------------------------------------
# 📘 2️⃣ Sequence Classification with LSTM
# --------------------------------------------
model = Sequential([
    Embedding(input_dim=len(tokenizer.word_index) + 1, output_dim=8, input_length=padded.shape[1]),
    LSTM(16),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded, labels, epochs=10, verbose=0)

# Test with a new review
test_text = ["The movie was really boring"]
test_seq = tokenizer.texts_to_sequences(test_text)
test_pad = pad_sequences(test_seq, maxlen=padded.shape[1], padding='post')
pred = model.predict(test_pad)
print("\n🎯 Sequence Classification Output:")
print("Sentence:", test_text[0])
print("Predicted Sentiment:", "Positive 😊" if pred[0][0] > 0.5 else "Negative 😞")

# --------------------------------------------
# 💬 3️⃣ LSTM for Text Generation & Sentiment Analysis
# --------------------------------------------
# Using the same trained model for a mini text generation logic
# (This is a simple demonstration of predictive text)
seed_text = "the"
print("\n📝 Text Generation Example:")
for _ in range(4):
    seq = tokenizer.texts_to_sequences([seed_text])
    pad = pad_sequences(seq, maxlen=padded.shape[1], padding='post')
    pred = model.predict(pad, verbose=0)
    next_word = np.random.choice(list(tokenizer.word_index.keys()))
    seed_text += " " + next_word
    print(seed_text)

print("\n✅ Sentiment Analysis Example Completed Successfully!")

📘 Word Index (meaning of each word):
{'this': 1, 'movie': 2, 'i': 3, 'was': 4, 'and': 5, 'love': 6, 'terrible': 7, 'fantastic': 8, 'acting': 9, 'story': 10, 'hated': 11, 'film': 12, 'amazing': 13, 'direction': 14, 'music': 15, 'the': 16, 'boring': 17}

🔢 Padded Sequences (converted text):
[[ 3  6  1  2]
 [ 1  2  4  7]
 [ 8  9  5 10]
 [ 3 11  1 12]
 [13 14  5 15]
 [16  2  4 17]]


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step

🎯 Sequence Classification Output:
Sentence: The movie was really boring
Predicted Sentiment: Negative 😞

📝 Text Generation Example:
the amazing
the amazing amazing
the amazing amazing and
the amazing amazing and the

✅ Sentiment Analysis Example Completed Successfully!
